version: "2"
services:
    client:
        image: FROM node:10
        restart: always
        ports:
            - "3000:3000"
        working_dir: /src/app
        volumes:
            - ./client:/src/app
        entrypoint: ["npm", "start"]
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: webapp-api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./server:/server
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge